### PR TITLE
Kicad7 upgrade

### PR DESCRIPTION
**Pull request by dl8dtl**
This upgrades everything to Kicad 7 (also ought to work with Kicad 8).

Library objects have been updated to their current counterparts from official Kicad where applicable.

All DRC errors have been fixed.

Additional layers added to Gerber that can be used to file it at commercial PCB manufacturers.

Supposed to fix issue #1

### CODE REVIEW

**Comment by aewallin** [comment]
hi @dl8dtl , thanks for your work on this! I opened the schematic and PCB with Kicad8 after your first PR, and seems to work ok on my machine (kicad 8.0.2 on ubuntu 22.04LTS).
for this second one there is a merge conflict - maybe you can rebase on the current master.
kicad files are probably not the easiest to put in git, so the conflict might be something trivial..

the 2014 images in the repo were apparently not linked to in the readme? It would be good to show a new image (or 3D render) in the readme now that the 3D printed enclosure-parts are included.

**Comment by dl8dtl** [comment]
Hello Anders, as you already merged PR #3 – that one contained all the changes from this PR here, so it became obsoleted by that. But I needed to upgrade everything to a modern Kicad before being able to continue with the new RJ45 magjack, that's why I started with this PR here.

Regarding images in the README file, I didn't change anything. My own part is not yet ready. Right now, I could only contribute a Kicad 3D view of it. As soon as it is ready to go, I can contribute new images, and link them in the README file.

**Comment by aewallin** [comment]
Thanks for the info, good luck with building the DSOXLAN board

**Comment by dl8dtl** [comment]
> Regarding images in the README file, I didn't change anything. My own part is not yet ready.

It's ready now, I'm going to prepare a pull request for updating the README file.

Actually, I built a slightly different variant in the end, as someone donated me another Würth RJ45 jack which has a different pinout. Since Kicad doesn't support schematics/PCB variants, I'd just keep the alternative layout in a branch in my fork though.

**Comment by dl8dtl** [comment]
dsoxlan-front
html5control

Teaser :-)

**Pull request closed without merging**
